import type { Artist } from './types';

export const artists: Artist[] = [
  {
    id: '1',
    name: 'Elena Vox',
    category: 'Singer',
    location: 'New York, NY',
    feeRange: '$1000 - $2500',
    bio: 'Soulful vocalist with a powerful stage presence, known for her captivating performances of jazz and blues classics. Trained at Juilliard.',
    image: 'https://placehold.co/400x400.png',
    languages: ['English', 'Spanish'],
  },
  {
    id: '2',
    name: 'DJ Spinmaster',
    category: 'DJ',
    location: 'Miami, FL',
    feeRange: '$2500+',
    bio: 'High-energy DJ specializing in electronic dance music and hip-hop. Has performed at major festivals including Ultra and Tomorrowland.',
    image: 'https://placehold.co/400x400.png',
    languages: ['English'],
  },
  {
    id: '3',
    name: 'Aria Moves',
    category: 'Dancer',
    location: 'Los Angeles, CA',
    feeRange: '$500 - $1000',
    bio: 'Versatile contemporary dancer and choreographer. Her expressive movements tell compelling stories, leaving audiences mesmerized.',
    image: 'https://placehold.co/400x400.png',
    languages: ['English', 'French'],
  },
  {
    id: '4',
    name: 'Dr. Ken Igma',
    category: 'Speaker',
    location: 'Chicago, IL',
    feeRange: '$2500+',
    bio: 'Motivational speaker and author focusing on leadership and innovation. His engaging talks inspire audiences to achieve their full potential.',
    image: 'https://placehold.co/400x400.png',
    languages: ['English'],
  },
  {
    id: '5',
    name: 'Leo harmonize',
    category: 'Singer',
    location: 'Nashville, TN',
    feeRange: '$500 - $1000',
    bio: 'Acoustic singer-songwriter with a folk-pop style. His heartfelt lyrics and smooth melodies are perfect for intimate events.',
    image: 'https://placehold.co/400x400.png',
    languages: ['English'],
  },
  {
    id: '6',
    name: 'Beatbreaker',
    category: 'DJ',
    location: 'Las Vegas, NV',
    feeRange: '$1000 - $2500',
    bio: 'Renowned for his open-format sets, blending genres from funk to house. The life of any party and a master of the dance floor.',
    image: 'https://placehold.co/400x400.png',
    languages: ['English'],
  },
   {
    id: '7',
    name: 'Rhythmic Feet',
    category: 'Dancer',
    location: 'New York, NY',
    feeRange: '$1000 - $2500',
    bio: 'A dynamic hip-hop and breakdance crew that brings explosive energy and incredible acrobatic skills to every performance.',
    image: 'https://placehold.co/400x400.png',
    languages: ['English'],
  },
  {
    id: '8',
    name: 'Jane Chen',
    category: 'Speaker',
    location: 'San Francisco, CA',
    feeRange: '$1000 - $2500',
    bio: 'Tech entrepreneur and futurist who speaks on the impact of artificial intelligence and the future of work. A thought-leader from Silicon Valley.',
    image: 'https://placehold.co/400x400.png',
    languages: ['English', 'German'],
  },
];
